---
- hosts: ubuntu
  become: true
  tasks:
    - name: install apache2 package
      apt: name=apache2 state=present
      #become: true
    - name: start apache service
      service: name=apache2 state=started
      #become: true
    - name: remove default index.html
      file: dest=/var/www/html/index.html state=absent
    - name: copy custom index.html file
      copy: content="Hello folks" dest=/var/www/html/index.html
